x = str(5)
x = int(5)
x = float(5)
x = complex(1j)

x = list(("apple", "banana", "cherry"))	
x = tuple(("apple", "banana", "cherry"))	
x = set(("apple", "banana", "cherry"))	
x = dict(name = 'Akash Mallik', age = 25)
x = frozenset(("apple", "banana", "cherry"))
x = bool(5)		
x = bytes(5)		
x = bytearray(5)
x = memoryview(bytes(5))			
print(x)
print(type(x))